name = "nbidal18 Vanilla+"
version = "1.0.73"
description = "Minecraft 26.2 vanilla+ modpack with automatic Prism updates"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f2c120e073e77ecedc2dd749a434fe0a71f7792c4ab117fed0dde1bf3ead2df"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
